name = "PorousConvection"
uuid = "cafc6ffa-5a0c-11ed-26ac-67a5ffa378df"
authors = ["Ludovic RÃ¤ss <ludovic.rass@gmail.com>"]
version = "0.1.0"

[deps]
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
